name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""
      - name: Download Parsec Mock, install dependencies and execute all tests
        uses: ./.github/actions/mock_tests

  build-msrv:
    name: MSRV - Build and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.66.0
          rustflags: ""
      - name: Download Parsec Mock, install dependencies and execute all tests
        uses: ./.github/actions/mock_tests
